# Resto das suas configurações...
database:
  tipo: "mysql"
  mysql:
    host: "78.46.164.171"
    porta: "3306"
    nome: "db_839857"
    usuario: "db_839857"
    senha: "4pCNi2el56Tx0bSN95l9"
    hikari: false
    mariadb: false
  mongodb:
    url: ""
